### ISSUE TITLE
Do you have any plans on supporting other browsers any time soon?

### ISSUE THREAD

**Issue by shotexa** [foyer-work/ooogle-it#25]
Just a question, I'm interested if you are planning to work on enabling this extension in safari or firefox.

**Comment by siddsax** [comment]
Thanks for checking us out! We actually already have a version on Firefox but due to some compatibility issues. It's on a slightly older version. Although it works the same. We are planning to bring that on parity soon. 

As for Safari that is not yet on our roadmap but if enough people need it then we can surely look into the same.

**Comment by shotexa** [comment]
> Thanks for checking us out! We actually already have a version on Firefox but due to some compatibility issues. It's on a slightly older version. Although it works the same. We are planning to bring that on parity soon.
> 
> As for Safari that is not yet on our roadmap but if enough people need it then we can surely look into the same.

Thanks for the response
